### ISSUE TITLE
Game does not resume when switching back and forth between tabs

### ISSUE THREAD

**Issue by ThaisRobba** [MassiveHeights/Black#60] opened 2019-03-18 17:07 UTC
**Describe the bug**
Game stops running after changing tabs multiple times.

**To Reproduce**
1. Go to [Draw Bounds Example](https://blacksmith2d.io/Docs/Examples/Game-Object/Draw-Bounds)
2. Change tabs twice
3. Come back to the Draw Bounds tab
4. Notice the game has stopped
5. Change to a different tab
6. Come back to the Draw Bounds tab
7. Change to a different tab
8. Come back to the Draw Bounds tab
9. Game will now have resumed

**Expected behavior**
Game is expected to always resume when its tab is selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 65.0.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72.0.3626.121

**Comment by 62316e** [comment] 2019-03-18 17:33
hi @ThaisRobba 
Adding those lines after starting Black should fix your issue.
```
black.pauseOnBlur = false;
black.pauseOnHide = false;
```

**Comment by ThaisRobba** [comment] 2019-03-18 18:40
Understood, thanks :)

It does seem to be a problem with the `onVisibilityChange` event (https://github.com/MassiveHeights/Black/blob/75400e38cfa4f1114798fdaf21a0e112bd142acd/src/Black.js#L294)

I'll try to debug it locally.

**Comment by ThaisRobba** [comment] 2019-03-18 19:54
Ok, did a bit of testing with the base template. The focus event is firing but it is not actually resuming the game because the `document.hidden` flag is still set to true. Clicking on the canvas does not fire a second "focus" event and thus, the game is stuck until you switch to a different tab (or select the developer console).

Changing `document.hidden` to `document.hasFocus()` seems to solve this, but I haven't tested it enough to feel confident that this doesn't break other things.

**Comment by 62316e** [comment] 2019-03-21 21:29
Hi @ThaisRobba 
I'm not able to reproduce this issue. Would you be so kind as to send me some video (maybe)?

**Comment by ThaisRobba** [comment] 2019-03-21 23:41
Sure thing. Made a tiny video, on a new private window:

https://youtu.be/Dq-HSx_LPOA

I've checked locally and, oddly enough, document.hidden sometimes returns true even though document.hasFocus() is also true. I'm not sure if it is inherent to Firefox, if it is a race condition... but document.hasFocus() seems to work fine.

Although, maybe the document.hidden check could actually be removed, since the engine is already checking for the event type?

**Comment by 62316e** [comment] 2019-03-22 11:26
Thanks for sharing the video. I can confirm to have same issue randomly.

I just tried this PR: https://github.com/MassiveHeights/Black/pull/49
Looks like it fix the issue

**Comment by ThaisRobba** [comment] 2019-03-22 19:12
I'll try it later today when I'm home :)

**Comment by ThaisRobba** [comment] 2019-03-23 05:10
That does seem to fix it!

**Comment by 62316e** [comment] 2019-06-26 08:36
Fixed in v0.5.10

**Closed by 62316e** 2019-06-26 08:36 UTC
